// Enums for the CoT application
// Note: Stored values use Code (EN), UI displays Label (KO)

export enum ProductCategory {
  SECURITIES = 'SECURITIES',
  INSURANCE = 'INSURANCE',
}

export enum ProductType {
  EQUITY = 'EQUITY',
  BOND = 'BOND',
  REIT = 'REIT',
  SHORT_TERM = 'SHORT_TERM',
  DERIVATIVE = 'DERIVATIVE',
  TRUST_PENSION = 'TRUST_PENSION',
  ANNUITY = 'ANNUITY',
  WHOLE_LIFE = 'WHOLE_LIFE',
  TERM = 'TERM',
  DISEASE = 'DISEASE',
  HEALTH = 'HEALTH',
  CANCER = 'CANCER',
  VARIABLE = 'VARIABLE',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum QuestionType {
  CUSTOMER_CHARACTERISTICS = 'CUSTOMER_CHARACTERISTICS',
  INVESTMENT_PREFERENCE = 'INVESTMENT_PREFERENCE',
  PRODUCT_COMPARISON = 'PRODUCT_COMPARISON',
  AGE_LIFECYCLE = 'AGE_LIFECYCLE',
  INVESTMENT_PRODUCT = 'INVESTMENT_PRODUCT',
  HEALTH_PROTECTION = 'HEALTH_PROTECTION',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum AgeBand {
  AGE_10 = 'AGE_10',
  AGE_20 = 'AGE_20',
  AGE_30 = 'AGE_30',
  AGE_40 = 'AGE_40',
  AGE_50 = 'AGE_50',
  AGE_60 = 'AGE_60',
  AGE_70 = 'AGE_70',
  AGE_80_PLUS = 'AGE_80_PLUS',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum CotStatus {
  DRAFT = 'DRAFT',
  REVIEW_REQUESTED = 'REVIEW_REQUESTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum CustomerRiskProfile {
  AGGRESSIVE = 'AGGRESSIVE',
  STABILITY_SEEKING = 'STABILITY_SEEKING',
  STABLE = 'STABLE',
  RISK_NEUTRAL = 'RISK_NEUTRAL',
  ACTIVE = 'ACTIVE',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum CrossSubscription {
  PROTECTION_ONLY = 'PROTECTION_ONLY',
  VARIABLE_ONLY = 'VARIABLE_ONLY',
  OTHER_ONLY = 'OTHER_ONLY',
  PROTECTION_VARIABLE = 'PROTECTION_VARIABLE',
  PROTECTION_OTHER = 'PROTECTION_OTHER',
  VARIABLE_OTHER = 'VARIABLE_OTHER',
  ALL_TYPES = 'ALL_TYPES',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum RiskGrade {
  GRADE_1 = 'GRADE_1',
  GRADE_2 = 'GRADE_2',
  GRADE_3 = 'GRADE_3',
  GRADE_4 = 'GRADE_4',
  GRADE_5 = 'GRADE_5',
  GRADE_6 = 'GRADE_6',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum TaxBenefit {
  YES = 'YES',
  NO = 'NO',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum PaymentType {
  LUMP_SUM = 'LUMP_SUM',
  ADDITIONAL = 'ADDITIONAL',
  MIXED = 'MIXED',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum Liquidity {
  REDEEMABLE = 'REDEEMABLE',
  NON_REDEEMABLE = 'NON_REDEEMABLE',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}
